// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type User struct {
	ID          int32
	FirebaseUid string
	Email       string
	FullName    string
	CreatedAt   time.Time
}
