// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    firebase_uid, 
    email, 
    full_name
) VALUES (
    $1, $2, $3
)
RETURNING id, firebase_uid, email, full_name, created_at
`

type CreateUserParams struct {
	FirebaseUid string
	Email       string
	FullName    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FirebaseUid, arg.Email, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}
